language: python
matrix:
    include:
       - language: python
                  - "2.7"
                  - "3.4"
                  - "3.5"
                  - "3.6"      
                  - "3.7"
                  - "3.8"
                  - "3.8-dev"
                  - "nightly"
         os: 
                  - linux
         install:
                  - pip install -r  Python_Version/requirements.txt
              # command to run tests
         before_script:
                  - echo "before"
                  - cd Python_Version/
         script:
                  - echo "script"
                  - python pygreetings.py
       - language: java
         jdk: openjdk9
         before_script: 
                  - echo "test before script hello"
         script: 
                  - echo "hello"

